apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.name" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.name" . }}
{{ include "prometheus.namespace" . | indent 4 }}
