{{- range $index, $item := .Values.prometheusInstances }}
{{- range $indexShard, $e := until (int (coalesce $item.shards 1)) }}
{{- if and (eq $.Values.thanos.enabled true) (eq $item.type "replica") }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.name" . }}-thanos-store-{{ $index }}-{{ $indexShard }}
spec:
  selector:
{{ include "common.selectorLabels" (dict "releaseName" "thanos-store") | indent 4 }}
{{ printf "instance: %s-%d-%d" $item.type $index $indexShard | indent 4 }}
  type: ClusterIP
  clusterIP: None
  ports:
    - name: thanos-http
      port: 19191
      targetPort: 19191
    - name: thanos-grpc
      port: 19090
      targetPort: 19090
{{- end }}
{{- end }}
{{- end }}